import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import type { Locale } from '@/i18n'
import { i18n } from '@/i18n'
import { LocaleProvider } from '@repo/i18n/client'

type Props = Readonly<{
  params: Readonly<{ lang: Locale }>
  children: React.ReactNode
}>

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    default: 'ban12.com',
    template: '%s | ban12.com',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params }: Props) {
  return (
    <html lang={params.lang}>
      <body className={`${inter.className} bg-gray-50 dark:bg-gray-900`}>
        <LocaleProvider locale={params.lang} i18n={i18n}>
          {children}
        </LocaleProvider>
      </body>
    </html>
  )
}
