import type { Metadata, Viewport } from 'next'

import '#/app/globals.css'

import { LocaleProvider } from '@repo/i18n/client'
import { Toaster } from '@repo/ui/components/sonner'
import { ThemeProvider } from 'next-themes'

import { i18n, type Locale } from '#/lib/i18n'

type Props = Readonly<{
  params: Promise<{ lang: Locale }>
  children: React.ReactNode
  drawer: React.ReactNode
}>

export const metadata: Metadata = {
  applicationName: 'Ban12',
  title: {
    default: 'Ban12',
    template: '%s | Ban12',
  },
  description: 'Generated by create next app',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Ban12',
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: 'website',
    siteName: 'Ban12',
    title: {
      default: 'Ban12',
      template: '%s | Ban12',
    },
    description: 'Generated by create next app',
  },
  icons: {
    icon: { url: '/api/og?w=48&h=48&bg=transparent', type: 'image/png' },
    shortcut: { url: '/api/og?w=192&h=192&bg=transparent', type: 'image/png' },
    apple: [
      { url: '/api/og?w=64&h=64&bg=transparent', type: 'image/png' },
      {
        url: '/api/og?w=180&h=180&bg=transparent',
        sizes: '180x180',
        type: 'image/png',
      },
    ],
  },
}

export const viewport: Viewport = {
  themeColor: '#FFFFFF',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export async function generateStaticParams() {
  return Object.keys(i18n.locales).map((lang) => ({ lang }))
}

export default async function RootLayout(props: Props) {
  const params = await props.params

  const { children, drawer } = props

  return (
    <html suppressHydrationWarning lang={params.lang}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LocaleProvider locale={params.lang} i18n={i18n}>
            {children}
            {drawer}
          </LocaleProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
