services:
  shortcuts:
    # build:
    #   context: .
    #   dockerfile: apps/shortcuts/Dockerfile
    #   args:
    #     - TURBO_TEAM=${TURBO_TEAM}
    #     - TURBO_TOKEN=${TURBO_TOKEN}
    #     - AUTH_SECRET=${AUTH_SECRET}
    image: cooda/ban12-site-shortcuts:latest
    env_file:
      - .env.shortcuts
    restart: always
    ports:
      - 3000:3000
    volumes:
      - shortcuts:/app/apps/shortcuts
    networks:
      - app_network

  toys:
    image: cooda/ban12-site-toys:latest
    restart: always
    ports:
      - 3001:3000
    volumes:
      - toys:/app/apps/toys
    networks:
      - app_network

  web:
    image: cooda/ban12-site-web:latest
    restart: always
    ports:
      - 3002:3000
    volumes:
      - web:/app/apps/web
    networks:
      - app_network

  nginx:
    image: macbre/nginx-http3
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp # use UDP for usage of HTTP/3
    volumes:
      - shortcuts:/app/apps/shortcuts
      - toys:/app/apps/toys
      - web:/app/apps/web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/modules.conf:/etc/nginx/main.d/modules.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/live/ban12.com/fullchain.pem:/etc/letsencrypt/live/ban12.com/fullchain.pem:ro
      - /etc/letsencrypt/live/ban12.com/privkey.pem:/etc/letsencrypt/live/ban12.com/privkey.pem:ro
    networks:
      - app_network

volumes:
  shortcuts:
  toys:
  web:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
