packages:
  - apps/*
  - packages/*

catalog:
  '@google/genai': ^1.5.1
  '@types/node': ^24.0.3
  postcss: ^8.5.6
  typescript: ^5.8.3
  intl-messageformat: ^10.7.16
  next-auth: 5.0.0-beta.28
  '@auth/drizzle-adapter': ^1.9.1
  '@simplewebauthn/browser': ^9.0.1
  '@simplewebauthn/server': ^9.0.3
  next-themes: ^0.4.6
  react-hook-form: ^7.58.1
  '@hookform/resolvers': ^5.1.1
  lucide-react: ^0.485.0
  gsap: ^3.13.0
  '@gsap/react': ^2.1.2
  babel-plugin-react-compiler: 19.1.0-rc.2
  zod: ^3.25.67
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  server-only: ^0.0.1
  next: ^15.3.3
  '@next/third-parties': ^15.3.3
  '@next/bundle-analyzer': ^15.3.3
  eslint-config-next: ^15.3.3
  '@next/eslint-plugin-next': ^15.3.3
  eslint: ^9.29.0
  turbo: ^2.5.4
  eslint-plugin-turbo: ^2.5.4
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-label': ^2.1.2
  '@radix-ui/react-navigation-menu': ^1.2.5
  '@radix-ui/react-select': ^2.1.6
  '@radix-ui/react-slot': ^1.1.2
  '@radix-ui/react-toggle-group': ^1.1.2
  '@radix-ui/react-tooltip': ^1.1.8
  usehooks-ts: ^3.1.1
  postcss-import: ^16.1.0
  sonner: ^2.0.5
  '@sentry/nextjs': ^9.14.0
  react-virtualized-auto-sizer: ^1.0.26
  react-window: ^1.8.11
  '@types/react-window': ^1.8.8
  react-window-infinite-loader: ^1.0.10
  '@types/react-window-infinite-loader': ^1.0.9
  '@opennextjs/cloudflare': ^1.3.0
  wrangler: ^4.20.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.44.2
  dotenv: ^16.5.0
  vaul: ^1.1.2
  '@upstash/redis': ^1.35.0

catalogs:
  canary:
    next: 15.4.0-canary.103
    '@next/third-parties': 15.4.0-canary.103
    '@next/bundle-analyzer': 15.4.0-canary.103
    eslint-config-next: 15.4.0-canary.103
    '@next/eslint-plugin-next': 15.4.0-canary.103

onlyBuiltDependencies:
  - '@vercel/speed-insights'
