packages:
  - "apps/*"
  - "packages/*"

catalogs:
  # Can be referenced through "catalog:react18"
  react18:
    "react": "^18.2.0"
    "react-dom": "^18.2.0"
    "@types/react": "^18.3.5"
    "@types/react-dom": "^18.2.25"

  next14:
    "next": "^14.2.9"
    "@next/third-parties": "^14.2.9"
    "@next/bundle-analyzer": "^14.2.9"
    "eslint-config-next": "^14.2.9"

  eslint8:
    "eslint": "^8.57.0"