packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": "^22.10.1"
  "postcss": "^8.4.49"
  "tailwind-merge": "^2.5.4"
  "tailwindcss": "^3.4.15"
  "typescript": "^5.7.2"
  "intl-messageformat": "^10.7.7"
  "next-themes": "^0.4.3"
  "react-hook-form": "^7.53.2"
  "lucide-react": "^0.456.0"
  "gsap": "^3.12.5"
  "babel-plugin-react-compiler": "19.0.0-beta-df7b47d-20241124"
  "class-variance-authority": "0.7.1"

catalogs:
  # Can be referenced through "catalog:react18"
  react19:
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "@types/react": "^19"
    "@types/react-dom": "^19"

  next15:
    "next": "^15.0.4"
    "@next/third-parties": "^15.0.4"
    "@next/bundle-analyzer": "^15.0.4"
    "eslint-config-next": "^15.0.4"
    "@next/eslint-plugin-next": "^15.0.4"
  
  eslint9:
    "eslint": "^9.16.0"

  turbo:
    "turbo": "^2.3.3"
    "eslint-plugin-turbo": "^2.3.3"
