packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": "^22.10.2"
  "postcss": "^8.4.49"
  "tailwind-merge": "^2.5.5"
  "tailwindcss": "^3.4.17"
  "typescript": "^5.7.2"
  "intl-messageformat": "^10.7.7"
  "next-themes": "^0.4.4"
  "react-hook-form": "^7.54.2"
  "lucide-react": "^0.469.0"
  "gsap": "^3.12.5"
  "babel-plugin-react-compiler": "19.0.0-beta-df7b47d-20241124"
  "class-variance-authority": "0.7.1"
  "zod": "3.24.1"
  "@ban12/tailwindcss-safe-area": "^0.2.4"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  "next": "^15.1.6"
  "@next/third-parties": "^15.1.6"
  "@next/bundle-analyzer": "^15.1.6"
  "eslint-config-next": "^15.1.6"
  "@next/eslint-plugin-next": "^15.1.6"
  "eslint": "^9.17.0"
  "turbo": "^2.4.2"
  "eslint-plugin-turbo": "^2.4.2"
  "@cloudflare/next-on-pages": "^1.13.2"
  "eslint-plugin-next-on-pages": "^1.13.2"
