packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/node': '^22.13.5'
  'postcss': '^8.5.3'
  'tailwind-merge': '^2.5.5'
  'tailwindcss': '^3.4.17'
  'typescript': '^5.7.3'
  'intl-messageformat': '^10.7.7'
  'next-themes': '^0.4.4'
  'react-hook-form': '^7.54.2'
  'lucide-react': '^0.469.0'
  'gsap': '^3.12.7'
  '@gsap/react': '^2.1.2'
  'babel-plugin-react-compiler': '19.0.0-beta-e1e972c-20250221'
  'class-variance-authority': '0.7.1'
  'zod': '3.24.1'
  '@ban12/tailwindcss-safe-area': '^0.2.4'
  'react': '^19.0.0'
  'react-dom': '^19.0.0'
  '@types/react': '^19'
  '@types/react-dom': '^19'
  'next': '^15.2.3'
  '@next/third-parties': '^15.2.3'
  '@next/bundle-analyzer': '^15.2.3'
  'eslint-config-next': '^15.2.3'
  '@next/eslint-plugin-next': '^15.2.3'
  'eslint': '^9.21.0'
  'turbo': '^2.4.4'
  'eslint-plugin-turbo': '^2.4.4'
  '@radix-ui/react-icons': '^1.3.2'
  '@radix-ui/react-label': '^2.1.2'
  '@radix-ui/react-navigation-menu': '^1.2.5'
  '@radix-ui/react-select': '^2.1.6'
  '@radix-ui/react-slot': '^1.1.2'
  '@radix-ui/react-toggle-group': '^1.1.2'
  '@radix-ui/react-tooltip': '^1.1.8'
  'usehooks-ts': '^3.1.1'
