packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/node': '^22.13.14'
  'postcss': '^8.5.3'
  'typescript': '^5.8.3'
  'intl-messageformat': '^10.7.7'
  'next-themes': '^0.4.6'
  'react-hook-form': '^7.55.0'
  '@hookform/resolvers': '^5.0.1'
  'lucide-react': '^0.485.0'
  'gsap': '^3.12.7'
  '@gsap/react': '^2.1.2'
  'babel-plugin-react-compiler': '19.1.0-rc.1'
  'zod': '^3.24.2'
  'react': '^19.1.0'
  'react-dom': '^19.1.0'
  '@types/react': '^19.1.0'
  '@types/react-dom': '^19.1.2'
  'next': '^15.3.1'
  '@next/third-parties': '^15.3.1'
  '@next/bundle-analyzer': '^15.3.1'
  'eslint-config-next': '^15.3.1'
  '@next/eslint-plugin-next': '^15.3.1'
  'eslint': '^9.23.0'
  'turbo': '^2.5.0'
  'eslint-plugin-turbo': '^2.5.0'
  '@radix-ui/react-icons': '^1.3.2'
  '@radix-ui/react-label': '^2.1.2'
  '@radix-ui/react-navigation-menu': '^1.2.5'
  '@radix-ui/react-select': '^2.1.6'
  '@radix-ui/react-slot': '^1.1.2'
  '@radix-ui/react-toggle-group': '^1.1.2'
  '@radix-ui/react-tooltip': '^1.1.8'
  'usehooks-ts': '^3.1.1'
  'postcss-import': '^16.1.0'
  'sonner': '^2.0.3'
  '@sentry/nextjs': '^9.14.0'
  'react-virtualized-auto-sizer': '^1.0.26'
  'react-window': '^1.8.11'
  '@types/react-window': '^1.8.8'
  'react-window-infinite-loader': '^1.0.10'
  '@types/react-window-infinite-loader': '^1.0.9'
  'server-only': '^0.0.1'
  '@opennextjs/cloudflare': '^1.0.0'
  'wrangler': '^4.14.1'
