packages:
  - apps/*
  - packages/*

catalog:
  '@auth/drizzle-adapter': ^1.10.0
  '@google/genai': ^1.15.0
  '@gsap/react': ^2.1.2
  '@hookform/resolvers': ^5.2.1
  '@next/bundle-analyzer': ^16.0.1
  '@next/eslint-plugin-next': ^16.0.1
  '@next/third-parties': ^16.0.1
  '@opennextjs/cloudflare': ^1.11.1
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-label': ^2.1.2
  '@radix-ui/react-navigation-menu': ^1.2.5
  '@radix-ui/react-select': ^2.1.6
  '@radix-ui/react-slot': ^1.1.2
  '@radix-ui/react-toggle-group': ^1.1.2
  '@radix-ui/react-tooltip': ^1.1.8
  '@sentry/nextjs': ^10.23.0
  '@simplewebauthn/browser': ^9.0.1
  '@simplewebauthn/server': ^9.0.3
  '@types/node': ^24.3.0
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@types/react-window': ^1.8.8
  '@types/react-window-infinite-loader': ^1.0.9
  '@upstash/redis': ^1.35.3
  babel-plugin-react-compiler: ^1.0.0
  dotenv: ^16.5.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.4
  eslint: ^9.34.0
  eslint-config-next: ^16.0.7
  eslint-plugin-turbo: ^2.5.8
  gsap: ^3.13.0
  intl-messageformat: ^10.7.16
  lucide-react: ^0.541.0
  next: ^16.0.7
  next-auth: 5.0.0-beta.30
  next-themes: ^0.4.6
  postcss: ^8.5.6
  postcss-import: ^16.1.0
  react: ^19.2.0
  react-dom: ^19.2.0
  react-hook-form: ^7.62.0
  react-virtualized-auto-sizer: ^1.0.26
  react-window: ^1.8.11
  react-window-infinite-loader: ^1.0.10
  recharts: ^2.15.4
  server-only: ^0.0.1
  sonner: ^2.0.7
  turbo: ^2.5.8
  typescript: ^5.9.2
  usehooks-ts: ^3.1.1
  vaul: ^1.1.2
  wrangler: ^4.46.0
  zod: ^4.0.17

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - bufferutil
  - esbuild
  - protobufjs
  - sharp
  - workerd

overrides:
  react-is: ^19.1.0
