packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": "^22.9.0"
  "postcss": "^8.4.49"
  "tailwind-merge": "^2.5.4"
  "tailwindcss": "^3.4.15"
  "typescript": "^5.6.3"
  "intl-messageformat": "^10.7.7"
  "next-themes": "^0.4.3"
  "react-hook-form": "^7.53.2"
  "lucide-react": "^0.456.0"
  "gsap": "^3.12.5"
  "babel-plugin-react-compiler": "19.0.0-beta-a7bf2bd-20241110"

catalogs:
  # Can be referenced through "catalog:react18"
  react18:
    "react": "^18.2.0"
    "react-dom": "^18.2.0"
    "@types/react": "^18.3.5"
    "@types/react-dom": "^18.2.25"

  react19:
    "react": "19.0.0-rc-66855b96-20241106"
    "react-dom": "19.0.0-rc-66855b96-20241106"
    "@types/react": "npm:types-react@rc"
    "@types/react-dom": "npm:types-react-dom@rc"

  next14:
    "next": "^14.2.13"
    "@next/third-parties": "^14.2.13"
    "@next/bundle-analyzer": "^14.2.13"
    "eslint-config-next": "^14.2.13"

  next15:
    "next": "^15.0.3"
    "@next/third-parties": "^15.0.3"
    "@next/bundle-analyzer": "^15.0.3"
    "eslint-config-next": "^15.0.3"
    "@next/eslint-plugin-next": "^15.0.3"

  eslint8:
    "eslint": "^8.57.0"
  
  eslint9:
    "eslint": "^9.14.0"

  turbo:
    "turbo": "^2.3.2"
    "eslint-plugin-turbo": "^2.3.2"
