[package]
name = "calculate_hash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
sha2 = "0.10.7"
wasm-bindgen = "0.2.87"

[profile.release]
lto = true
opt-level = 3
