import {
  AppWindow,
  BedDouble,
  Briefcase,
  Building2,
  Calendar,
  ClipboardPen,
  Clock,
  FileText,
  Globe,
  GraduationCap,
  Handshake,
  Landmark,
  MapIcon,
  MountainSnow,
  Plane,
  QrCode,
  ShieldCheck,
  Smartphone,
  TrainFront,
  Users,
  Wallet,
  Wifi,
} from 'lucide-react';

export const IconMap = {
  'file-text': FileText,
  calendar: Calendar,
  wallet: Wallet,
  'shield-check': ShieldCheck,
  landmark: Landmark,
  building: Building2,
  globe: Globe,
  'mountain-snow': MountainSnow,
  wifi: Wifi,
  smartphone: Smartphone,
  'train-front': TrainFront,
  'app-window': AppWindow,
  'map-icon': MapIcon,
  clock: Clock,
  users: Users,
  'clipboard-pen': ClipboardPen,
  'qr-code': QrCode,
  'bed-double': BedDouble,
  plane: Plane,
  'graduation-cap': GraduationCap,
  briefcase: Briefcase,
  handshake: Handshake,
  'map-pin': MapIcon, // Mapping map-pin to MapIcon as commonly used
} as const;

export type IconName = keyof typeof IconMap;
